apiVersion: v1
kind: Service
metadata:
  name: tomcat-app
spec:  
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
  type: ClusterIP
  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-front
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30010

    - name: https
      port: 443
      targetPort: 443
      nodePort: 30043

  type: NodePort