apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ratriv/testapp_backend
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ratriv/testapp_frontend
        ports:
        - containerPort: 80
        - containerPort: 443